### ISSUE TITLE
Parsing compile command line doesn't return expect result (none cmake project)

### ISSUE THREAD

**Issue by zhongweiy** [LefterisJP/malinka#5]
Hi, Lefteris,

Here is one compile command line from a project called [opus](http://downloads.xiph.org/releases/opus/opus-1.1.tar.gz) (output from `make -n`):
```
echo "  CC      " silk/control_codec.lo;depbase=`echo silk/control_codec.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
        /bin/bash ./libtool --silent --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I.  -I./include -I./celt -I./silk -I./silk/float -I./silk/fixed   -g -O2 -fvisibility=hidden -W -Wall -Wextra -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -MT s\
ilk/control_codec.lo -MD -MP -MF $depbase.Tpo -c -o silk/control_codec.lo silk/control_codec.c &&\
        mv -f $depbase.Tpo $depbase.Plo
```
And I get following result:
```
{"directory":"~/project/opus/opus/","command":"gcc \t/bin/bash ./libtool --silent --tag=CC  --mode=compile -std=gnu99 -g -O2 -fvisibility=hidden -W -Wall -Wextra -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -MT silk/control_codec.lo -MD -MP -MF $depbas\
   e.Tpo &&\\ -DHAVE_CONFIG_H -I/home/zhongwei/project/opus/opus -I/home/zhongwei/project/opus/opus/include -I/home/zhongwei/project/opus/opus/celt -I/home/zhongwei/project/opus/opus/silk -I/home/zhongwei/project/opus/opus/silk/float -I/home/zhongwei/project/opus/opus/\
   silk/fixed -c -o /home/zhongwei/project/opus/opus/silk/control_codec.o /home/zhongwei/project/opus/opus/silk/control_codec.c","file":"/home/zhongwei/project/opus/opus/silk/control_codec.c"}
```
Above command will call error when run with clang because of ` \t/bin/bash ./libtool --silent --tag=CC  --mode=compile`, which is not a part of compile command line.

By the way, I get some debug info from `malinka--configoutput-process-line` function:
```
Malinka-debug: path-list: (/home/zhongwei/project/opus/opus/silk control_codec.c)
Malinka-debug: attributes-list: ((HAVE_CONFIG_H) (. ./include ./celt ./silk ./silk/float ./silk/fixed) (        /bin/bash ./libtool --silent --tag=CC  --mode=compile -std=gnu99 -g -O2 -fvisibility=hidden -W -Wall -Wextra -Wcast-align -Wnested-externs -Wshadow -Wstr\
    ict-prototypes -MT silk/control_codec.lo -MD -MP -MF $depbase.Tpo &&\))
```

I feel only keep string start from compile name (gcc here) to end when processing the command line can solve problem in my case. But I feel it may not work under other case (like there is extra environment var setting before compile name, I'm not sure though). What do you think?

Thanks!

**Comment by LefterisJP** [comment]
@zhongweiy I download opus and tried to configure it with malinka. My configuration is like:
```elisp
(malinka-define-project
 :name "opus"
 :root-directory "/home/lefteris/Downloads/opus-1.1"
 :build-directory "/home/lefteris/Downloads/opus-1.1"
 :configure-cmd "make -n"
 :compile-cmd "make"
 :test-cmd "")
```

I get ouput like this in the `compile_commands.json` which is obviously wrong.

```json
{"directory":"/home/lefteris/Downloads/opus-1.1/","command":"gcc /bin/sh ./libtool --silent --tag=CC  --mode=compile -g -O2 -fvisibility=hidden -W -Wall -Wextra -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -MT celt/quant_bands.lo -MD -MP -MF $depbase.Tpo &&\\ -DHAVE_CONFIG_H -I/home/lefteris/Downloads/opus-1.1 -I/home/lefteris/Downloads/opus-1.1/include -I/home/lefteris/Downloads/opus-1.1/celt -I/home/lefteris/Downloads/opus-1.1/silk -I/home/lefteris/Downloads/opus-1.1/silk/float -I/home/lefteris/Downloads/opus-1.1/silk/fixed -c -o /home/lefteris/Downloads/opus-1.1/celt/quant_bands.o /home/lefteris/Downloads/opus-1.1/celt/quant_bands.c","file":"/home/lefteris/Downloads/opus-1.1/celt/quant_bands.c"},
```

I am afraid that it's not very easy to fix this since the makefile's output in this case is quite complicated. This is one of the cases where malinka can't work nicely at the moment since make's output has calls to `echo` and `sed`.

It's because the makefile has lots of crazy stuff in it like this:
```Make
.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CC)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LTCOMPILE) -c -o $@ $<
```

**Comment by zhongweiy** [comment]
Yeah, it seems not trivial. Does malinka have a plan to support more complex command line?

Because there are a lot projects are not cmake based.

**Comment by LefterisJP** [comment]
In principle, malinka supports any project as it tries to parse the compile commands. As your example project shows, this does not work fine all the time. We have users, myself included, who use it for non-cmake projects succesfully though.

There are always going to be edge cases and Opus seems to be one of them. My time is limited so I don't know if/when I can make this work properly without breaking everything else.

If you really need this and can figure out a way to implement it patches are more than welcome.

Let's keep this issue open until then.

**Comment by zhongweiy** [comment]
I try to use Malinka on [Coreutils](http://www.gnu.org/software/coreutils/coreutils.html) today. And get stuck on similar issue as in Opus.

And I find [Bear](https://github.com/rizsotto/Bear) works on Opus and Coreutils. What it is needed to do when configure project is to replace `make -n` with `bear make`. But comparing with parsing command line in Malinka itself, it introduces extra dependence (user has to install Bear manually). What do you think about this idea?

If you would like see more details, here it is: https://github.com/zhongweiy/malinka/commit/3a94316656e22dac9a22b069936ff0ad7b01e773

**Comment by LefterisJP** [comment]
So my goal would be to at some point be able to parse all command line arguments succesfully without any external help. As you can see there are these edge cases still, but if I have time or if someone else finds time for a patch that would be awesome.

I like the idea of using `bear` if the user has it installed in his system but I would like to propose a different way to implement it.

1. There should be a setup phase of malinka, which would check the user's system and see if the executable `bear` exists anywhere in the path. If it does it would set some kind of global `malinka-have-bear` flag.

2. When configuring the project, if it's not a cmake project but we have bear, then `bear` should be prepended to the given compile command. The output of the command should be processed as you showed in your PR.

3.  In other cases we do as before

Do you think you can open a PR based on your linked commit that would be doing what I described above? I can do it myself but you had the idea and already put some effort into it :)

**Comment by zhongweiy** [comment]
Sure, I can try to open a PR:)

>When configuring the project, if it's not a cmake project but we have bear, then bear should be prepended to the given compile command. 

But As I know, other build system like [ninja](https://martine.github.io/ninja/manual.html) also can generate compilation database. So it will have problem when we have bear install and configure a ninja project.

So insteading handle generating compilation database for various build tool, I'm thinking whether we could provide an option that let user provide the exact command that can generate compile command if they could, like:
```
(malinka-define-project
 :name "ethereum"
 :root-directory "/home/lefteris/ew/cpp-ethereum"
 :build-directory "/home/lefteris/ew/cpp-ethereum/build"
 :compile-db-cmd "cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
 :configure-cmd "cmake .. -DCMAKE_BUILD_TYPE=Debug -DHEADLESS=1"
 :compile-cmd "make -j4"
 :test-cmd "./test/testeth")
```

What do you think?

**Comment by LefterisJP** [comment]
I like the idea. You do indeed have a point that this may not work well with ninja. But on the other hand we could have some logic in the processing of `configure-cmd` to see if it is ninja. If it is then just use the ninja compilation database command. `ninja -t compdb TARGET`?

The reason I suggest this is because we can have malinka do more work and the user do less so that it's an easy to use project manager. We could still have the `compile-db-cmd` but as an optional attribute. If it's given then we use that, if not try to see if the user is using ninja, if he is using cmake, if the user's system has bear e.t.c.

So something like this:

1. If `compile-db-cmd` is given,  use it to create `compile_commands.json` and go to 5
2. If `configure-cmd` is given:
    1. If it's cmake, keep the current functionality as it is which is generating the compdb with `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON` and go to 5
   2. If it's ninja use the ninja way to create the database and go to 5
3. If the user's system has bear, prepend that to the compilation command to create the database and go to 5.
4. In other cases try to manually parse the compilation command (as malinka is currently doing) and create the compilation database ourselves and go to 5.
5. Feed the compilation database to rtags, flycheck and other programs. I would like to have other backends added, like [emacs-ycmd](https://github.com/abingham/emacs-ycmd). And all of them should be optional. Even rtags. Malinka should be able to see what the user has, and send it the data it requires.

So that's the general plan :)
I am pretty busy with my day-job for this week and the next so I don't think I will have any time to start this but who knows. I simply wanted to share this with you since you seem to be pretty interested.

**Comment by zhongweiy** [comment]
sorry for the late reply. I got your idea, let me have a try:)
